version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: expenses-postgres
    environment:
      POSTGRES_DB: expensesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - expenses-network

  redis:
    image: redis:7-alpine
    container_name: expenses-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - expenses-network

  expenses-api:
    build: ./java-expenses
    container_name: expenses-api
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/expensesdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    networks:
      - expenses-network

volumes:
  postgres_data:
  redis_data:

networks:
  expenses-network:
    driver: bridge